<form action="entry" method="post">

    <fieldset class="input-legend">
        <legend class="input-legend">Natureza</legend>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-expense" value="expense">
            <label for="entry_nature-expense">Despesa</label>
        </div>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-revenue" value="revenue">
            <label for="entry_nature-revenue">Receita</label>
        </div>
        
    </fieldset>

    <div class="box-input label-row">
        <label for="entry_value" class="input-legend">Valor</label>
        <input type="tel" name="entry_value" id="entry_value" step=".01" placeholder="0,00">
    </div>

    <div class="box-input label-row">
        <label for="entry_release_date" class="input-legend">Data de lançamento</label>
        <input type="date" name="entry_release_date" id="entry_release_date">
    </div>

    <fieldset class="input-legend">
        <legend class="input-legend">Tipo</legend>

        <div class="box-input">
            <input type="radio" name="entry_type" id="account" value="account">
            <label for="account">Conta corrente</label>    
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_type" id="credit" value="credit">
            <label for="credit">Crédito</label>                
        </div>        

    </fieldset>

    <div class="box-input label-row">
        <label for="entry_description" class="input-legend">Descrição da despesa</label>
        <textarea name="entry_description" id="entry_description"></textarea>
    </div>
    
    <fieldset class="input-legend">
        <legend class="input-legend">Recorrencia</legend>

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="no_recurrence" value="no_recurrence">
            <label for="no_recurrence">Sem recorrência</label>
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="installment" value="installment">
            <label for="installment">Parcelar</label>            
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="fixed" value="fixed">
            <label for="fixed">Fixa</label>            
        </div>        
    </fieldset>
        
    <div class="box-input label-row">
        <label for="entry_category" class="input-legend">Categoria</label>
        <input type="text" name="entry_category" id="entry_category">
    </div>
    
    <div class="box-input label-row">
        <label for="entry_subcategory" class="input-legend">Subcategoria</label>
        <input type="text" name="entry_subcategory" id="entry_subcategory">
    </div>

    <div class="box-input box-toggle">
        <input type="checkbox" name="entry_effected" id="effected-yes" value="1" hidden>
        <label for="effected-yes" class="input-legend" id="event-key-toggle" tabindex="0">
            Efetivada
            <div class="input-toggle"></div>
        </label>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    
</form>