<form action="entry" method="post">

    <fieldset>
        <legend>Natureza</legend>

        <select name="entry_nature" id="entry_nature">
            <option value="revenue">Receita</option>
            <option value="expense">Despesa</option>
        </select>

    </fieldset>

    <label for="entry_value">Valor</label>
    <input type="number" name="entry_value" id="entry_value" step="0.01">

    <label for="entry_release_date">Data de lançamento</label>
    <input type="date" name="entry_release_date" id="entry_release_date">

    <fieldset>
        <legend>Tipo</legend>

        <input type="radio" name="entry_type" id="account" value="account">
        <label for="account">Conta corrente</label>

        <input type="radio" name="entry_type" id="credit" value="credit">
        <label for="credit">Crédito</label>

    </fieldset>

    <label for="entry_description">Descrição da despesa</label>
    <textarea name="entry_description" id="entry_description"></textarea>

    <fieldset>
        <legend>Recorrencia</legend>

        <input type="radio" name="entry_recurrence" id="no_recurrence" value="no_recurrence">
        <label for="no_recurrence">Sem recorrência</label>

        <input type="radio" name="entry_recurrence" id="installment" value="installment">
        <label for="installment">Parcelar</label>

        <input type="radio" name="entry_recurrence" id="fixed" value="fixed">
        <label for="fixed">Fixa</label>
    </fieldset>

    <fieldset>
        <legend>Efetivada</legend>

        <input type="radio" name="entry_effected" id="effected-yes" value="yes">
        <label for="effected-yes">Sim</label>

        <input type="radio" name="entry_effected" id="effected-no" value="no">
        <label for="effected-no">Não</label>

    </fieldset>

    <label for="entry_category">Categoria</label>
    <input type="text" name="entry_category" id="entry_category">

    <label for="entry_subcategory">Subcategoria</label>
    <input type="text" name="entry_subcategory" id="entry_subcategory">

    <button type="submit">Registrar</button>

    <span>alteração</span>
    
</form>