
    <?php
        use MF\Model\Container;
        $entrys = Container::getModel( 'Entry' );

        //$entry->get_entrys_for_month();
        $month = date('m');
        $year = date('Y');
        $getEntrys = $entrys->get_entrys_for_month( $month, $year );


        //print_r( $entrys->get_entrys_for_month( 3 ) );
        //print_r( array_column( $getEntrys, 'entry_nature', 'entry_value' ) );

        print_r( 'Entrada: ' . $entrys->get_value_total_entrys( $getEntrys, 'revenue' ) );
        echo '<br>';
        print_r( 'Saída: ' . $entrys->get_value_total_entrys( $getEntrys, 'expense' ) );
        echo '<hr>';
        print_r( 'Saldo: ' . $entrys->get_value_balance( $getEntrys ) );
        
    ?>


<div class="box-input" style="flex-direction: column; align-items: end; margin-bottom: 20px;">
    <label for="entry_month">Mês de Referência: </label>
    <input type="month" name="entry_month" id="entry_month" value="<?php echo date('Y-m'); ?>">
</div>

<h2 class="section-title accordeon-open" tabindex="0"><span>Registrar Lançamento</span><i class="fas fa-arrow-alt-circle-down"></i></h2>

<form action="entry" method="post" id="form-entry">

    <fieldset class="input-legend">
        <legend class="input-legend">Natureza</legend>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-expense" value="expense">
            <label for="entry_nature-expense">Despesa</label>
        </div>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-revenue" value="revenue">
            <label for="entry_nature-revenue">Receita</label>
        </div>
        
    </fieldset>

    <div class="box-input label-row">
        <label for="entry_value" class="input-legend">Valor</label>
        <input type="tel" name="entry_value" id="entry_value" step=".01" placeholder="0,00">
    </div>

    <div class="box-input label-row">
        <label for="entry_expected_date" class="input-legend">Data de lançamento</label>
        <input type="date" name="entry_expected_date" id="entry_expected_date">
    </div>

    <fieldset class="input-legend">
        <legend class="input-legend">Tipo</legend>

        <div class="box-input">
            <input type="radio" name="entry_type" id="account" value="account">
            <label for="account">Conta corrente</label>    
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_type" id="credit" value="credit">
            <label for="credit">Crédito</label>                
        </div>        

    </fieldset>

    <div class="box-input label-row">
        <label for="entry_description" class="input-legend">Descrição da despesa</label>
        <textarea name="entry_description" id="entry_description"></textarea>
    </div>
    
    <fieldset class="input-legend">
        <legend class="input-legend">Recorrencia</legend>

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="no_recurrence" value="no_recurrence">
            <label for="no_recurrence">Sem recorrência</label>
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="installment" value="installment">
            <label for="installment">Parcelar</label>            
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="fixed" value="fixed">
            <label for="fixed">Fixa</label>            
        </div>        
    </fieldset>
        
    <div class="box-input label-row">
        <label for="entry_category" class="input-legend">Categoria</label>
        <input type="text" name="entry_category" id="entry_category">
    </div>
    
    <div class="box-input label-row">
        <label for="entry_subcategory" class="input-legend">Subcategoria</label>
        <input type="text" name="entry_subcategory" id="entry_subcategory">
    </div>

    <div class="box-input box-toggle">
        <input type="checkbox" name="entry_effected" class="effected-yes" id="effected-yes" value="1" hidden>
        <label for="effected-yes" class="input-legend event-key-toggle" id="" tabindex="0">
            Efetivada
            <div class="input-toggle"></div>
        </label>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    
</form>

<h2 class="section-title accordeon-open" tabindex="0"><span>Lançamentos</span><i class="fas fa-arrow-alt-circle-down"></i></h2>

<div id="display-entry-sumary">

    <?php foreach( $getEntrys as $key => $entry ) : ?>

        <div class="card-sumary <?php echo $entry['entry_nature'] == 'expense' ? 'expense' : 'revenue' ?> <?php echo $entry['entry_recurrence'] == 'installment' ? 'installment' : '' ?>" id="entry-card-<?php  echo $entry['id']; ?>">
        
            <div class="icon-card">
                <?php echo $entry['entry_nature'] == 'expense' ? '<i class="fa-solid fa-arrow-trend-down"></i>' : '<i class="fa-solid fa-arrow-trend-up"></i>' ?>
            </div>

            <div class="box-input box-toggle">
                <input type="checkbox" name="entry_id" class="effected-yes" id="entry-<?php echo $entry['id']; ?>" value="1" hidden <?php echo $entry['entry_effected']; ?> <?php echo $entry['entry_effected'] != '0' ? 'checked' : ''; ?>>
                <label for="entry-<?php echo $entry['id']; ?>" class="input-legend event-key-toggle" id="" tabindex="0">
                    <?php echo $entry['entry_expected_date'] ?>
                    <div class="input-toggle"></div>
                </label>
            </div>

            <div class="content-card-sumary">
                <div class="arrown-one">
                    <h3 class="entry-name"><?php echo $entry['entry_description'] ?></h3>
                    <a href="" class="edit-entry">
                        <span class="btn-icon">
                            <i class="fas fa-pencil-alt"></i>
                        </span>
                    </a>
                    
                </div>
        
                <div class="arrown-two">
                    <?php echo $entrys->format_entry_recurrence( $entry['entry_recurrence'] ); ?>

                    <?php if( $entry['entry_recurrence'] == 'installment' ) { ?>
                         - <?php echo $entrys->get_installment_for_month( $month, $entry['id_for_entry'] ); ?> / <?php echo $entry['entry_qty_installments'] . ' ( '. $entrys->sum_values_entry_installments( $entry['id_for_entry'] ) .' )' ?>
                    <?php } ?>

                </div>
        
                <div class="arrown-tree">
                    <div class="entry-tags">
                        <span class="entry-price"><?php echo $entrys->format_entry_value( $entry['entry_value'] ); ?></span>
                        <span class="entry-category btn-icon"><i class="fa-brands fa-cc-mastercard"></i></i><?php echo $entry['entry_category']; ?></span>
                    </div>
                    <a href="" class="remove-entry" id="remove-entry-<?php echo $entry['id']; ?>">
                        <span class="btn-icon">
                            <i class="fa-solid fa-trash-can"></i>
                        </span>
                    </a>
                </div>
            </div>

            <form action="edit_entry" method="post" class="form-edity-entry" id="form-edity-entry">
                <fieldset class="input-legend">
                    <legend class="input-legend">Natureza</legend>

                    <div class="box-input">
                        <input type="radio" name="edit_entry_nature" id="edit_entry_nature-expense-<?php echo $entry['id']?>" value="expense" <?php echo $entry['entry_nature'] == 'expense' ? 'checked' : '' ; ?>>
                        <label for="edit_entry_nature-expense-<?php echo $entry['id']?>">Despesa</label>
                    </div>

                    <div class="box-input">
                        <input type="radio" name="edit_entry_nature" id="edit_entry_nature-revenue-<?php echo $entry['id']?>" value="revenue" <?php echo $entry['entry_nature'] == 'revenue' ? 'checked' : '' ; ?>>
                        <label for="edit_entry_nature-revenue-<?php echo $entry['id']?>">Receita</label>
                    </div>
                    
                </fieldset>

                <div class="box-input label-row">
                    <label for="edit_entry_value_<?php echo $entry['id']; ?>" class="input-legend">Valor</label>
                    <input type="tel" name="edit_entry_value" id="edit_entry_value_<?php echo $entry['id']; ?>" class="input-entry-value" step=".01" placeholder="0,00" <?php echo isset( $entry['entry_value'] ) ? 'value="' . str_replace( '.', ',', $entry['entry_value'] ) . '"' : '' ; ?>>
                </div>

                <div class="box-input label-row">
                    <label for="edit_entry_expected_date-<?php echo $entry['id']?>" class="input-legend">Data de lançamento</label>
                    <input type="date" name="edit_entry_expected_date" id="edit_entry_expected_date-<?php echo $entry['id']?>" <?php echo isset( $entry['entry_expected_date'] ) ? 'value="' . $entrys->get_entry_expected_date_html_for_id( $entry['id'] ) . '"' : '' ?>>
                    
                </div>

                <fieldset class="input-legend">
                    <legend class="input-legend">Tipo</legend>

                    <div class="box-input">
                        <input type="radio" name="edit_entry_type" id="account-<?php echo $entry['id']?>" value="account" <?php echo $entry['entry_type'] == 'account' ? 'checked' : '' ; ?>>
                        <label for="account-<?php echo $entry['id']?>">Conta corrente</label>    
                    </div>        

                    <div class="box-input">
                        <input type="radio" name="edit_entry_type" id="credit-<?php echo $entry['id']?>" value="credit" <?php echo $entry['entry_type'] == 'credit' ? 'checked' : '' ; ?>>
                        <label for="credit-<?php echo $entry['id']?>">Crédito</label>                
                    </div>        

                </fieldset>

                <div class="box-input label-row">
                    <label for="edit_entry_description-<?php echo $entry['id']?>" class="input-legend">Descrição da despesa</label>
                    <textarea name="edit_entry_description" id="edit_entry_description-<?php echo $entry['id']?>"><?php echo isset( $entry['entry_description'] ) ? $entry['entry_description'] : '' ?></textarea>
                </div>
                
                <fieldset class="input-legend">
                    <legend class="input-legend">Recorrencia</legend>

                    <div class="box-input">
                        <input type="radio" name="edit_entry_recurrence" id="edit_no_recurrence-<?php echo $entry['id']; ?>" value="no_recurrence" <?php echo $entry['entry_recurrence'] == 'no_recurrence' ? 'checked' : '' ; ?>>
                        <label for="edit_no_recurrence-<?php echo $entry['id']; ?>">Sem recorrência</label>
                    </div>        

                    <div class="box-input">
                        <input type="radio" name="edit_entry_recurrence" id="edit_installment-<?php echo $entry['id']; ?>" class="installment-recurrence" value="installment" <?php echo $entry['entry_recurrence'] == 'installment' ? 'checked' : '' ; ?>>
                        <label for="edit_installment-<?php echo $entry['id']; ?>">Parcelar</label>            
                    </div>        

                    <div class="box-input">
                        <input type="radio" name="edit_entry_recurrence" id="edit_fixed-<?php echo $entry['id']; ?>" value="fixed" <?php echo $entry['entry_recurrence'] == 'fixed' ? 'checked' : '' ; ?>>
                        <label for="edit_fixed-<?php echo $entry['id']; ?>">Fixa</label>            
                    </div>        
                </fieldset>

                <?php 
                    if( $entry['entry_recurrence'] == 'installment' ) { ?>
                        <div id="installments-<?php echo $entry['entry_recurrence']; ?>" class="box-input label-row installments-toggle">
                            <label for="entry_qty_installments-<?php echo $entry['entry_recurrence']; ?>" class="input-legend">Quantidade de parcelas</label>
                            <input type="number" name="entry_qty_installments-<?php echo $entry['entry_recurrence']; ?>" id="entry_qty_installments-<?php echo $entry['entry_recurrence']; ?>" value="<?php echo $entry['entry_qty_installments']?>">
                        </div>
                    <?php }
                ?>
                    
                <div class="box-input label-row">
                    <label for="edit_entry_category-<?php echo $entry['id']?>" class="input-legend">Categoria</label>
                    <input type="text" name="edit_entry_category" id="edit_entry_category-<?php echo $entry['id']?>" <?php echo isset( $entry['entry_category'] ) ? 'value="' . $entry['entry_category'] . '"' : '' ?>>
                </div>
                
                <div class="box-input label-row">
                    <label for="edit_entry_subcategory-<?php echo $entry['id']?>" class="input-legend">Subcategoria</label>
                    <input type="text" name="edit_entry_subcategory" id="edit_entry_subcategory-<?php echo $entry['id']?>" <?php echo isset( $entry['entry_subcategory'] ) ? 'value="' . $entry['entry_subcategory'] . '"' : '' ?>>
                </div>

                <input type="hidden" name="entry_id" value="<?php echo $entry['id']; ?>">
                
                <button type="submit" class="btn btn-primary">Alterar</button>
            </form>

        </div>

    <?php endforeach; ?>
    
</div>