
    <?php
        use MF\Model\Container;
        $entrys = Container::getModel( 'Entry' );

        //$entry->get_entrys_for_month();
        $getEntrys = $entrys->get_entrys_for_month( 4 );


        //print_r( $entrys->get_entrys_for_month( 3 ) );
        //print_r( array_column( $getEntrys, 'entry_nature', 'entry_value' ) );

        print_r( 'Entrada: ' . $entrys->get_value_total_entrys( $getEntrys, 'revenue' ) );
        echo '<br>';
        print_r( 'Saída: ' . $entrys->get_value_total_entrys( $getEntrys, 'expense' ) );
        echo '<hr>';
        print_r( 'Saldo: ' . $entrys->get_value_balance( $getEntrys ) );
        
    ?>



<h2 class="section-title accordeon-open" tabindex="0"><span>Registrar Lançamento</span><i class="fas fa-arrow-alt-circle-down"></i></h2>

<form action="entry" method="post" id="form-entry">

    <fieldset class="input-legend">
        <legend class="input-legend">Natureza</legend>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-expense" value="expense">
            <label for="entry_nature-expense">Despesa</label>
        </div>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-revenue" value="revenue">
            <label for="entry_nature-revenue">Receita</label>
        </div>
        
    </fieldset>

    <div class="box-input label-row">
        <label for="entry_value" class="input-legend">Valor</label>
        <input type="tel" name="entry_value" id="entry_value" step=".01" placeholder="0,00">
    </div>

    <div class="box-input label-row">
        <label for="entry_expected_date" class="input-legend">Data de lançamento</label>
        <input type="date" name="entry_expected_date" id="entry_expected_date">
    </div>

    <fieldset class="input-legend">
        <legend class="input-legend">Tipo</legend>

        <div class="box-input">
            <input type="radio" name="entry_type" id="account" value="account">
            <label for="account">Conta corrente</label>    
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_type" id="credit" value="credit">
            <label for="credit">Crédito</label>                
        </div>        

    </fieldset>

    <div class="box-input label-row">
        <label for="entry_description" class="input-legend">Descrição da despesa</label>
        <textarea name="entry_description" id="entry_description"></textarea>
    </div>
    
    <fieldset class="input-legend">
        <legend class="input-legend">Recorrencia</legend>

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="no_recurrence" value="no_recurrence">
            <label for="no_recurrence">Sem recorrência</label>
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="installment" value="installment">
            <label for="installment">Parcelar</label>            
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="fixed" value="fixed">
            <label for="fixed">Fixa</label>            
        </div>        
    </fieldset>
        
    <div class="box-input label-row">
        <label for="entry_category" class="input-legend">Categoria</label>
        <input type="text" name="entry_category" id="entry_category">
    </div>
    
    <div class="box-input label-row">
        <label for="entry_subcategory" class="input-legend">Subcategoria</label>
        <input type="text" name="entry_subcategory" id="entry_subcategory">
    </div>

    <div class="box-input box-toggle">
        <input type="checkbox" name="entry_effected" class="effected-yes" id="effected-yes" value="1" hidden>
        <label for="effected-yes" class="input-legend event-key-toggle" id="" tabindex="0">
            Efetivada
            <div class="input-toggle"></div>
        </label>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    
</form>

<h2 class="section-title accordeon-open" tabindex="0"><span>Lançamentos</span><i class="fas fa-arrow-alt-circle-down"></i></h2>

<form action="up_entry" method="post" id="form-entry-sumary">

    <?php foreach( $getEntrys as $key => $entry ) : ?>

        <div class="card-sumary <?php echo $entry['entry_nature'] == 'expense' ? 'expense' : 'revenue' ?>" id="<?php  echo $entry['id']; ?>">
        
            <div class="icon-card">
                <?php echo $entry['entry_nature'] == 'expense' ? '<i class="fa-solid fa-arrow-trend-down"></i>' : '<i class="fa-solid fa-arrow-trend-up"></i>' ?>
            </div>

            <div class="content-card-sumary">
                <div class="arrown-one">
                    <h3 class="entry-name"><?php echo $entry['entry_description'] ?></h3>
                    <div class="box-input box-toggle">
                        <input type="checkbox" name="entry_id" class="effected-yes" id="entry-<?php echo $entry['id']; ?>" value="1" hidden <?php echo $entry['entry_effected']; ?> <?php echo $entry['entry_effected'] != '0' ? 'checked' : ''; ?>>
                        <label for="entry-<?php echo $entry['id']; ?>" class="input-legend event-key-toggle" id="" tabindex="0">
                            <?php echo $entry['entry_expected_date'] ?>
                            <div class="input-toggle"></div>
                        </label>
                    </div>
                </div>
        
                <div class="arrown-two">
                    <?php echo $entrys->format_entry_recurrence( $entry['entry_recurrence'] ); ?>
                </div>
        
                <div class="arrown-tree">
                    <div class="entry-tags">
                        <span class="entry-price"><?php echo $entrys->format_entry_value( $entry['entry_value'] ); ?></span>
                        <span class="entry-category btn-icon"><i class="fa-brands fa-cc-mastercard"></i></i><?php echo $entry['entry_category']; ?></span>
                    </div>
                    <a href="" class="edit-entry">
                        <span class="btn-icon">
                            <i class="fas fa-pencil-alt"></i>
                        </span>
                    </a>
                </div>
            </div>

        </div>

    <?php endforeach; ?>

    

    <div class="card-sumary revenue">
        
        <div class="icon-card">
            <i class="fa-solid fa-arrow-trend-up"></i>
        </div>

        <div class="content-card-sumary">
            <div class="arrown-one">
                <h3 class="entry-name">Cartão Inter</h3>
                <div class="box-input box-toggle">
                    <input type="checkbox" name="entry_id" class="effected-yes" id="entry-id-0" value="1" hidden>
                    <label for="entry-id-0" class="input-legend event-key-toggle" id="" tabindex="0">
                        26/03/25
                        <div class="input-toggle"></div>
                    </label>
                </div>
            </div>
    
            <div class="arrown-two">
                Despesa fixa
            </div>
    
            <div class="arrown-tree">
                <div class="entry-tags">
                    <span class="entry-price">R$ 905,86</span>
                    <span class="entry-category btn-icon"><i class="fa-brands fa-cc-mastercard"></i></i>Fatura Fechada</span>
                </div>
                <a href="" class="edit-entry"><span class="btn-icon"><i class="fas fa-pencil-alt"></i></span></a>
            </div>
        </div>

    </div>
</form>