<?php
    use MF\Model\Container;
    $entrys = Container::getModel( 'Entry' );

    $month = date('m');
    $year = date('Y');

?>


<div class="box-input" style="flex-direction: column; align-items: end; margin-bottom: 20px;">
    <label for="entry_month">Mês de Referência: </label>
    <input type="month" name="entry_month" id="entry_month" value="<?php echo date('Y-m'); ?>">
</div>

<h2 class="section-title accordeon-open" tabindex="0"><span>Registrar Lançamento</span><i class="fas fa-arrow-alt-circle-down"></i></h2>

<form action="entry" method="post" id="form-entry">

    <fieldset class="input-legend">
        <legend class="input-legend">Natureza</legend>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-expense" value="expense">
            <label for="entry_nature-expense">Despesa</label>
        </div>

        <div class="box-input">
            <input type="radio" name="entry_nature" id="entry_nature-revenue" value="revenue">
            <label for="entry_nature-revenue">Receita</label>
        </div>
        
    </fieldset>

    <div class="box-input label-row">
        <label for="entry_value" class="input-legend">Valor</label>
        <input type="tel" name="entry_value" id="entry_value" step=".01" placeholder="0,00">
    </div>

    <div class="box-input label-row">
        <label for="entry_expected_date" class="input-legend">Data de lançamento</label>
        <input type="date" name="entry_expected_date" id="entry_expected_date">
    </div>

    <fieldset class="input-legend">
        <legend class="input-legend">Tipo</legend>

        <div class="box-input">
            <input type="radio" name="entry_type" id="account" value="account">
            <label for="account">Conta corrente</label>    
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_type" id="credit" value="credit">
            <label for="credit">Crédito</label>                
        </div>        

    </fieldset>

    <div class="box-input label-row">
        <label for="entry_description" class="input-legend">Descrição da despesa</label>
        <textarea name="entry_description" id="entry_description"></textarea>
    </div>
    
    <fieldset class="input-legend">
        <legend class="input-legend">Recorrencia</legend>

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="no_recurrence" value="no_recurrence">
            <label for="no_recurrence">Sem recorrência</label>
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="installment" value="installment">
            <label for="installment">Parcelar</label>            
        </div>        

        <div class="box-input">
            <input type="radio" name="entry_recurrence" id="fixed" value="fixed">
            <label for="fixed">Fixa</label>            
        </div>        
    </fieldset>
        
    <div class="box-input label-row">
        <label for="entry_category" class="input-legend">Categoria</label>
        <input type="text" name="entry_category" id="entry_category">
    </div>
    
    <div class="box-input label-row">
        <label for="entry_subcategory" class="input-legend">Subcategoria</label>
        <input type="text" name="entry_subcategory" id="entry_subcategory">
    </div>

    <div class="box-input box-toggle">
        <input type="checkbox" name="entry_effected" class="effected-yes" id="effected-yes" value="1" hidden>
        <label for="effected-yes" class="input-legend event-key-toggle" id="" tabindex="0">
            Efetivada
            <div class="input-toggle"></div>
        </label>
    </div>
    
    <button type="submit" class="btn btn-primary">Registrar</button>
    
</form>

<h2 class="section-title accordeon-open" tabindex="0"><span>Lançamentos</span><i class="fas fa-arrow-alt-circle-down"></i></h2>
<?php $entrys->get_format_display_entry_sumary( $month, $year ); ?>