<!DOCTYPE html>
<html lang="pt-BR">
	<head>

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>My Finance</title>

		<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

		<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->

		<link rel="stylesheet" type="text/css" href="/css/style.css">

	</head>

	<body>

		<?php
			use MF\Model\Container;
			$entrys = Container::getModel( 'Entry' );
			$month = date('m');
			$year = date('Y');
			$getEntrys = $entrys->get_entrys_for_month( $month, $year );
		?>

		<header>
			<div class="box-header">
				<div class="logo"></div>
				<div id="sumary-header">
					<div class="sumary-value <?php echo $entrys->get_value_balance( $getEntrys ) < 0 ? 'color-allert' : '';?>"><?php echo $entrys->get_value_balance( $getEntrys ) < 0 ? '- ' : '';?><?php echo $entrys->format_entry_value( abs( $entrys->get_value_balance( $getEntrys ) ) ); ?></div>
					<div class="show-sumary-value"><img src="icons/view-value.svg" alt=""></div>
				</div>
			</div>
		</header>

		<main>
			<?php echo $this->content(); ?>
		</main>
		
		<script src="js/script.js"></script>
	</body>

</html>